# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import image_stream_pb2 as nre_dot_grpc_dot_protos_dot_image__stream__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestImage = channel.unary_unary(
                '/nre.grpc.protos.stream.ImageService/GetLatestImage',
                request_serializer=nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageRequest.SerializeToString,
                response_deserializer=nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageResponse.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestImage,
                    request_deserializer=nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageRequest.FromString,
                    response_serializer=nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nre.grpc.protos.stream.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.stream.ImageService/GetLatestImage',
            nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageRequest.SerializeToString,
            nre_dot_grpc_dot_protos_dot_image__stream__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
