# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nre/grpc/protos/image_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"nre/grpc/protos/image_stream.proto\x12\x16nre.grpc.protos.stream\"\x84\x01\n\x0cImageRequest\x12\r\n\x05\x65go_x\x18\x01 \x01(\x02\x12\r\n\x05\x65go_y\x18\x02 \x01(\x02\x12\r\n\x05\x65go_z\x18\x03 \x01(\x02\x12\x10\n\x08\x65go_roll\x18\x04 \x01(\x02\x12\x11\n\tego_pitch\x18\x05 \x01(\x02\x12\x0f\n\x07\x65go_yaw\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\x06\"\xfb\x01\n\rImageResponse\x12\x18\n\x10\x66ront_left_image\x18\x01 \x01(\x0c\x12\x19\n\x11\x66ront_right_image\x18\x02 \x01(\x0c\x12\x1a\n\x12\x66ront_center_image\x18\x03 \x01(\x0c\x12\x18\n\x10left_front_image\x18\x04 \x01(\x0c\x12\x17\n\x0fleft_side_image\x18\x05 \x01(\x0c\x12\x17\n\x0fleft_rear_image\x18\x06 \x01(\x0c\x12\x19\n\x11right_front_image\x18\x07 \x01(\x0c\x12\x18\n\x10right_side_image\x18\x08 \x01(\x0c\x12\x18\n\x10right_rear_image\x18\t \x01(\x0c\x32m\n\x0cImageService\x12]\n\x0eGetLatestImage\x12$.nre.grpc.protos.stream.ImageRequest\x1a%.nre.grpc.protos.stream.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nre.grpc.protos.image_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=63
  _globals['_IMAGEREQUEST']._serialized_end=195
  _globals['_IMAGERESPONSE']._serialized_start=198
  _globals['_IMAGERESPONSE']._serialized_end=449
  _globals['_IMAGESERVICE']._serialized_start=451
  _globals['_IMAGESERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
